[request_definition]
r = sub, obj, act, scope

[policy_definition]
p = sub, obj, act, scope

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act && (p.scope == "any" || p.scope == r.scope)
